# Değişken Standirdizasyonu

In [1]:
import numpy as np
import pandas as pd

In [2]:
V1 = np.array([1,3,6,5,7])
V2  = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])

df = pd.DataFrame({"V1":V1,"V2":V2,"V3":V3})
df = df.astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      5 non-null      float64
 1   V2      5 non-null      float64
 2   V3      5 non-null      float64
dtypes: float64(3)
memory usage: 248.0 bytes


In [3]:
df


V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [4]:
from sklearn import preprocessing

In [5]:
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [8]:
df.mean()


V1    4.4
V2    7.8
V3    8.6
dtype: float64

# Normalizisyon

In [9]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

# Min-Max Dönüşümü

In [13]:
scaler = preprocessing.MinMaxScaler(feature_range=(10,200))

In [14]:
scaler.fit_transform(df)

array([[ 10.        ,  64.28571429,  31.11111111],
       [ 73.33333333,  64.28571429, 157.77777778],
       [168.33333333,  10.        ,  10.        ],
       [136.66666667,  91.42857143,  31.11111111],
       [200.        , 200.        , 200.        ]])

# Değişken Dönüşümleri

In [15]:
import seaborn as sns
df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# 0-1 Dönüşümü

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
lbe = LabelEncoder()

In [18]:
lbe.fit_transform(df["sex"])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [19]:
df["yeni_sex"] = lbe.fit_transform(df["sex"])

In [20]:
df

total_bill   tip     sex smoker   day    time  size  yeni_sex
0         16.99  1.01  Female     No   Sun  Dinner     2         0
1         10.34  1.66    Male     No   Sun  Dinner     3         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1
242       17.82  1.75    Male     No   Sat  Dinner     2         1
243       18.78  3.00  Female     No  Thur  Dinner     2         0

[244 rows x 8 columns]

# 1 ve 0 dönüşümü

In [21]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         0
1       10.34  1.66    Male     No  Sun  Dinner     3         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0

In [22]:
df["yeni_day"] = np.where(df["day"].str.contains("Sun"),1,0)

0    168
1     76
Name: yeni_day, dtype: int64

# Çok sınıflı dönüşüm

In [25]:
lbe = LabelEncoder()

In [26]:
lbe.fit_transform(df["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [27]:
# çok dikkat

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
 7   yeni_sex    244 non-null    int32   
 8   yeni_day    244 non-null    int32   
dtypes: category(4), float64(2), int32(2), int64(1)
memory usage: 9.3 KB


# One-Hot dönüşümü ve Dummy değişken tuzağı

In [29]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex  yeni_day
0       16.99  1.01  Female     No  Sun  Dinner     2         0         1
1       10.34  1.66    Male     No  Sun  Dinner     3         1         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0         1

In [30]:
df_one_hot = pd.get_dummies(df,columns = ["sex"],prefix=["sex"])

In [31]:
df_one_hot.head()

total_bill   tip smoker  day    time  size  yeni_sex  yeni_day  sex_Male  \
0       16.99  1.01     No  Sun  Dinner     2         0         1         0   
1       10.34  1.66     No  Sun  Dinner     3         1         1         1   
2       21.01  3.50     No  Sun  Dinner     3         1         1         1   
3       23.68  3.31     No  Sun  Dinner     2         1         1         1   
4       24.59  3.61     No  Sun  Dinner     4         0         1         0   

   sex_Female  
0           1  
1           0  
2           0  
3           0  
4           1

In [32]:
pd.get_dummies(df,columns = ["day"],prefix=["day"]).head()

total_bill   tip     sex smoker    time  size  yeni_sex  yeni_day  \
0       16.99  1.01  Female     No  Dinner     2         0         1   
1       10.34  1.66    Male     No  Dinner     3         1         1   
2       21.01  3.50    Male     No  Dinner     3         1         1   
3       23.68  3.31    Male     No  Dinner     2         1         1   
4       24.59  3.61  Female     No  Dinner     4         0         1   

   day_Thur  day_Fri  day_Sat  day_Sun  
0         0        0        0        1  
1         0        0        0        1  
2         0        0        0        1  
3         0        0        0        1  
4         0        0        0        1